# Generated by Django 5.1.4 on 2024-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_alter_modelcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcompany',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
    ]
