# Generated by Django 5.1.4 on 2024-12-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_modelfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfavorite',
            options={'verbose_name': 'Фаворит', 'verbose_name_plural': 'Фавориты'},
        ),
        migrations.AlterField(
            model_name='modelfavorite',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.modelgame', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='modelfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
