# Generated by Django 5.1.4 on 2024-12-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_alter_modelfavorite_options_alter_modelfavorite_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfavorite',
            name='favorite',
        ),
    ]
