# Generated by Django 5.1.4 on 2024-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_remove_modelfavorite_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgame',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
