# Generated by Django 5.1.4 on 2024-12-16 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_alter_modelgame_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelfavorite',
            unique_together={('user', 'game')},
        ),
    ]
